#created on: Nov 11, 2009
package org.openengsb

rule "eventbuildbreak"
	
	when
		e: Event ( name == "buildbreak" )
	then
		String cid = e.getContextId();
		if(cid != null){
			helper.sendNotification("ruledev@company.com", "rule malfanction", "A buildbreak-event occured with no contextId"); 
		} else {
			helper.sendNotification("qm@company.com", "[openEngsb] buildbreak notification", "Project with cid " + cid + " suffered a buildbreak");
			String today = new Date().toString();
			helper.createIssue("Build break " + today, "Project suffered a buildbreak on " + today);
		}
end

