package org.openengsb.drools

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.apache.servicemix.drools.model.Exchange;
import org.openengsb.drools.model.Event
import org.openengsb.drools.model.Action

import java.util.ArrayList

global org.apache.servicemix.drools.model.JbiHelper jbi;
global org.openengsb.drools.XmlHelper xml;

rule "Parse"
	when
		e : Exchange()
	then
		Event event = xml.parseEvent(e.getIn().getContent());
		insert(event);
		//insert(new Event("greet"));
end
	
rule "Test"
	when
		e: Event(name == "test", handled == false)
	then
		System.out.println("test");
		e.setHandled(true);
		insert(new Action("fault", "test-fault"));
end

rule "Cleanup"
	when
		e: Event()
	then
		e.setHandled(true);
end