/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.servicemix.drools
 
import org.apache.servicemix.drools.model.Exchange;

global org.apache.servicemix.drools.model.JbiHelper jbi;
 
rule "Unspecified id"
	when
		me : Exchange( status == Exchange.ACTIVE, $in : in != null )
		eval( $in.xpath("/test/@id <= 0") )
	then
		jbi.fault( "<fault>Id must be > 0</fault>" );
end

rule "Route to target1"
	when
		me : Exchange( status == Exchange.ACTIVE, $in : in != null )
		eval( $in.xpath("/test/@id = 1") )
	then
		jbi.route( "service::target1" );
end

rule "Route to target2"
	when
		me : Exchange( status == Exchange.ACTIVE, $in : in != null )
		eval( $in.xpath("/test/@id = 2") )
	then
		jbi.route( "service::target2" );
end

rule "Route to target3"
	when
		me : Exchange( status == Exchange.ACTIVE, $in : in != null )
		eval( $in.getProperty("prop") != null )
	then
		jbi.route( "service::target3" );
end

