#!/bin/sh
PREFIX="OPENENGSB"
ISSUEID=$(git branch | egrep -o "^\* $PREFIX-[[:digit:]]*" | sed s/"\* "//)
if [ -z "$ISSUEID" ]; then
  exit 0
fi

CONTENT=$(grep -v "^#" "$1" | sed s/"\[$ISSUEID\][[:space:]]*"// | sed s/"[[:space:]]"//g)
if [ -z "$CONTENT" ]; then
  echo > $1
fi
