#!/bin/sh
PREFIX="OPENENGSB"
SUMMARY=$(cat "$1" | head -n1)
ISSUEID=$(git branch | grep "^* $PREFIX" | egrep -o "$PREFIX\-[[:digit:]]+" )
if [ -z "$ISSUEID" ]; then
	exit 0
fi

if echo "$SUMMARY" | cut -c 1-15 | grep "$ISSUEID" > /dev/null; then
	exit 0
fi

echo "automatically prepending issue-id: $ISSUEID"

mv $1 $1.bak
echo "[$ISSUEID] $SUMMARY" > $1
awk 'FNR>1' "$1.bak" >> $1
rm $1.bak
