#
#   Copyright 2010 OpenEngSB Division, Vienna University of Technology
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

when
  e : Event( name == "commit")
then
  String author = e.getValue("author");

  Map emails = ctx.getAllValues("workflows/edbcommit/notification/email/");
  Set emailSet = emails.keySet();
  Iterator it = emailSet.iterator();
  boolean hasNext = it.hasNext();
  while(hasNext){
    String test = it.next();
    send(notification, author, test, "", "");
    hasNext = it.hasNext();
  }